"use strict";
define(["main-app", "tools",
    "core/common-controller",
    "core/animate/animate",
    "core/factory/user-config",
    "core/factory/button-interval",
    "core/factory/destroy",
    "core/factory/storage",
    "core/factory/http",
    "core/factory/fecha",
    "core/factory/delay",
    "core/factory/enum-data",
    "core/factory/validator",
    "core/factory/id-card",
    "core/factory/modal",
    "core/factory/window-resize",
    "core/factory/md5",
    "core/factory/cookie",
    "core/factory/notify",
    "core/factory/cache",
    "core/factory/esc-keydown",
    "core/directive/index-head/index-head",
    "core/directive/index-nav/index-nav",
    "core/directive/limit-span/limit-span",
    "core/directive/limit-span/td-limit-span",
    "core/directive/limit-span/no-bind-limit-span",
    "core/directive/table/table-box",
    "core/directive/table/table-sort",
    "core/directive/datetime-picker/ymd-picker",
    "core/directive/datetime-picker/ymdhms-picker",
    "core/directive/image/image-preview",
    "core/directive/key-search-select/key-search-select"
], function (app, tools) {

});